### ISSUE TITLE
Donation button closes the menu

### ISSUE THREAD

**Issue by Michael21107** [pnwparksfan/rph-live-lights#24]
any chance making clicking the donation button not close the menu?

**Comment by pnwparksfan** [comment]
This is expected behavior - same thing happens when opening the SSLA link. This was because I have it pause the game when opening a link externally, and if you un-pause the game by hitting esc then it closes the menu anyways because the menu will register the esc key, so you see the menu flash on screen for a moment when closing the game. 

I don't see it really being worth the effort to implement a workaround, but who knows, maybe if you make use of the donation button I will consider it ;)

**Comment by Michael21107** [comment]
i hear you ;)
